### ISSUE TITLE
How to prepare for a security review checklist

### ISSUE THREAD

**Issue by montyly** [crytic/building-secure-contracts#113]
We can convert our blogpost to a checklist: https://blog.trailofbits.com/2018/04/06/how-to-prepare-for-a-security-audit/

And we can add a couple of blockchain-specific points

**Comment by damilolaedwards** [comment]
- [ ] Enable and Address all compiler/linter warnings
- [ ] Increase unit and feature tests coverage
- [ ] Remove dead code, unused variables, functions, libraries and other extraneous weights 
- [ ] Provide external documentation and past security reviews / bug findings (if any)
- [ ] Use inline comments (preferably natspec for solidity)
- [ ] Label and describe your tests
- [ ] Document compilation and deployment process
- [ ] For solidity code, ensure slither runs successfully (document any required intermediate setup process if any)
- [ ] Ensure that the commit hash / branch/ release for the audit has been provided before the review commencement date
- [ ] Ensure all engineers assigned to the audit review have been invited to all relevant repositories before commencement date
